# terraform-docs configuration
# Generate documentation with: terraform-docs markdown . > README.md

formatter: markdown table

version: ">= 0.16.0"

header-from: header.md

sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

content: |
  {{ .Header }}

  ## Usage

  ```hcl
  module "pitfal_infrastructure" {
    source = "./infrastructure/terraform"

    project_name   = "pitfal"
    environment    = "prod"
    domain_name    = "pitfal.solutions"
    contact_email  = "info@pitfal.solutions"
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
